"""The one line of the push pipeline that a fake transport cannot cover: the call into ``pywebpush``.

Every other test injects a transport, which is what makes classification, the ledger, the retry
ladder and the pool testable without a network stack. The cost of that seam is that the real call —
VAPID signing, `aes128gcm` encryption, the headers pywebpush chooses — has nothing exercising it.
This closes that, against a local HTTP server standing in for a push service.

**Skipped when ``pywebpush`` is absent**, which is a real state: it is in the ``serve`` extra, so an
engine checkout without it installed still imports and still runs everything else. It is present in
the API image (``pip install ".[serve]"``), so this runs where it matters.

What this does NOT cover is a real push service's own behaviour — its rate limits, its interpretation
of TTL, its idea of when a subscription is gone. Nothing short of sending to Google or Mozilla covers
that, and the runbook says so.
"""

import base64
import http.server
import json
import subprocess
import sys
import threading
from pathlib import Path

import pytest

pytest.importorskip("pywebpush", reason="the push transport lives in the `serve` extra")
http_ece = pytest.importorskip("http_ece")
from cryptography.hazmat.primitives import serialization          # noqa: E402
from cryptography.hazmat.primitives.asymmetric import ec          # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "examples"))
import push_payload                                               # noqa: E402
import push_retry                                                 # noqa: E402
import push_sender                                                # noqa: E402


def _b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode().rstrip("=")


@pytest.fixture(scope="module")
def vapid(tmp_path_factory):
    """A real VAPID pair, generated by the exact recipe `docs/BROWSER_PUSH_OPERATIONS.md` §2 gives an
    operator — so this also tests the documentation. A recipe that produced a subtly wrong key would
    otherwise only fail in production, asynchronously, as a 401 from a push service."""
    pem = tmp_path_factory.mktemp("vapid") / "vapid.pem"
    script = f"""
    openssl ecparam -name prime256v1 -genkey -noout -out {pem}
    echo PUB=$(openssl ec -in {pem} -pubout -outform DER 2>/dev/null \
      | tail -c 65 | base64 | tr '/+' '_-' | tr -d '=\\n')
    echo PRIV=$(openssl ec -in {pem} -outform DER 2>/dev/null \
      | tail -c +8 | head -c 32 | base64 | tr '/+' '_-' | tr -d '=\\n')
    """
    out = subprocess.run(["bash", "-c", script], capture_output=True, text=True, check=True).stdout
    pair = dict(line.split("=", 1) for line in out.strip().splitlines())
    assert len(pair["PUB"]) == 87 and pair["PUB"].startswith("B"), "the runbook's own sanity check"
    assert len(pair["PRIV"]) == 43
    return pair


@pytest.fixture()
def device():
    """A browser's half of the subscription: a real P-256 keypair and a 16-byte auth secret, exactly
    what `pushManager.subscribe()` produces."""
    private = ec.generate_private_key(ec.SECP256R1())
    public = private.public_key().public_bytes(serialization.Encoding.X962,
                                               serialization.PublicFormat.UncompressedPoint)
    return {"private": private, "auth": b"0123456789abcdef", "p256dh": public}


@pytest.fixture()
def service():
    """A push service that records the request and answers by path: `/ok` 201, `/gone` 410, anything
    else 429 with a `Retry-After`."""
    received: dict = {}

    class _Handler(http.server.BaseHTTPRequestHandler):
        def do_POST(self):                        # noqa: N802 — BaseHTTPRequestHandler's spelling
            received["headers"] = {k.lower(): v for k, v in self.headers.items()}
            received["body"] = self.rfile.read(int(self.headers.get("Content-Length", 0)))
            code = 201 if "/ok" in self.path else (410 if "/gone" in self.path else 429)
            self.send_response(code)
            if code == 429:
                self.send_header("Retry-After", "120")
            self.end_headers()

        def log_message(self, *a):                # keep pytest output clean
            pass

    server = http.server.HTTPServer(("127.0.0.1", 0), _Handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    yield server.server_port, received
    server.shutdown()


def _payload() -> str:
    return push_payload.encode(push_payload.build(
        {"id": 7, "kind": "breaking_story", "dedupe_key": "ev:42",
         "created_at": "2026-07-30T11:00:00+00:00",
         "payload": {"storyId": "st_9", "title": "Court issues ruling", "publisherCount": 5}},
        lang="en", sent_at="2026-07-30T12:00:00+00:00"))


def _sender(vapid):
    # transport=None on purpose: this is the whole point — the real `_pywebpush_transport`.
    return push_sender.WebPushSender(private_key=vapid["PRIV"], subject="mailto:ops@example.com",
                                     timeout=10.0)


def test_a_real_send_is_signed_encrypted_and_accepted(vapid, device, service):
    port, received = service
    subscription = {"endpoint": f"http://127.0.0.1:{port}/ok",
                    "p256dh": _b64(device["p256dh"]), "auth": _b64(device["auth"])}

    result = _sender(vapid).send(subscription, _payload())
    assert result.ok and result.status_code == 201

    headers = received["headers"]
    assert headers["content-encoding"] == "aes128gcm"
    assert headers["authorization"].startswith("vapid ")
    assert vapid["PUB"] in headers["authorization"], "the public key travels in the VAPID header"


def test_the_transport_sends_the_ttl_the_retry_ladder_is_pinned_to(vapid, device, service):
    """`push_retry.MAX_DELIVERY_AGE_SECONDS` equals this number so the ladder never outlives the
    message. A unit test compares the two constants; this proves the one on the wire is real."""
    port, received = service
    _sender(vapid).send({"endpoint": f"http://127.0.0.1:{port}/ok",
                         "p256dh": _b64(device["p256dh"]), "auth": _b64(device["auth"])},
                        _payload())
    assert received["headers"]["ttl"] == str(int(push_retry.MAX_DELIVERY_AGE_SECONDS))


def test_the_payload_is_encrypted_and_decrypts_to_exactly_what_was_built(vapid, device, service):
    """The round trip, from the device's side. A push service sees ciphertext; only a holder of the
    subscription's private key sees the story headline."""
    port, received = service
    body = _payload()
    _sender(vapid).send({"endpoint": f"http://127.0.0.1:{port}/ok",
                         "p256dh": _b64(device["p256dh"]), "auth": _b64(device["auth"])}, body)

    assert b"Court issues ruling" not in received["body"], "not on the wire in plaintext"
    plain = http_ece.decrypt(received["body"], private_key=device["private"],
                             auth_secret=device["auth"], version="aes128gcm")
    assert json.loads(plain) == json.loads(body)


@pytest.mark.parametrize("path,status,code", [
    ("/ok", push_sender.SUCCESS, 201),
    ("/gone", push_sender.EXPIRED, 410),
    ("/busy", push_sender.TRANSIENT, 429),
])
def test_real_http_answers_classify_the_way_the_fakes_do(vapid, device, service, path, status, code):
    """The classification tests elsewhere drive `classify_status` directly. This proves the same
    answers come back out of a real request, including that pywebpush surfaces a non-2xx as an
    exception carrying the response rather than as a return value."""
    port, _ = service
    result = _sender(vapid).send({"endpoint": f"http://127.0.0.1:{port}{path}",
                                  "p256dh": _b64(device["p256dh"]), "auth": _b64(device["auth"])},
                                 _payload())
    assert result.status == status and result.status_code == code


def test_a_retry_after_from_a_real_429_reaches_the_ladder(vapid, device, service):
    """End to end for B3's floor: the header the service set, off a real response, parsed into the
    delay the scheduler will use."""
    port, _ = service
    result = _sender(vapid).send({"endpoint": f"http://127.0.0.1:{port}/busy",
                                  "p256dh": _b64(device["p256dh"]), "auth": _b64(device["auth"])},
                                 _payload())
    assert result.retry_after == "120"
    assert push_retry.parse_retry_after(result.retry_after) == 120.0


def test_an_unreachable_service_is_transient_not_permanent(vapid, device):
    """No server on the port at all — the connection-refused path, which only a real socket produces
    and which must not be mistaken for a bad request on our side."""
    result = _sender(vapid).send({"endpoint": "http://127.0.0.1:9/nothing-listens-here",
                                  "p256dh": _b64(device["p256dh"]), "auth": _b64(device["auth"])},
                                 _payload())
    assert result.status == push_sender.TRANSIENT
    assert push_retry.is_retryable(result.status)
