#!/usr/bin/env node
/**
 * build-sw-data — generate `public/sw-data.js` from the authoritative sources (Phase B2).
 *
 * The service worker is served verbatim from `public/`, so no bundler touches it and it cannot import
 * the metadata table or the i18n catalogs. It needs both to render a notification without a network
 * call (architecture §2 P4), and copying them by hand is exactly the drift §8 rejects.
 *
 * A GENERATED copy is not a duplicate — §8 says so explicitly, and this is what makes it true: the
 * table comes from `lib/notification-kinds.ts` and the strings from `messages/*.json`, both at build
 * time, so a change on either side reaches the worker or fails the build. Nothing here is edited by
 * hand and the output is not committed.
 *
 * Only the `notifications.*` subset of each catalog ships — 20 keys across five languages, under 7 KB
 * — which is small enough that sending every supported language to every device beats any scheme for
 * choosing one.
 *
 * Run: `node scripts/build-sw-data.mjs` (wired into `npm run build` and `npm run build:e2e`).
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";
import ts from "typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.resolve(__dirname, "..");

/**
 * Load the metadata table from its TypeScript source.
 *
 * **Not `import ... from "../lib/notification-kinds.ts"`**, which is what this did first and which
 * works only on Node ≥22.18, where type stripping is on by default. The production web image is
 * `node:20-slim`, where the same line fails the whole build with `ERR_UNKNOWN_FILE_EXTENSION` — a
 * blocker that never appeared in development because this machine runs Node 22, and never appeared
 * in CI because CI runs the same Node this machine does.
 *
 * Transpiling with the `typescript` already in devDependencies is version-proof: it works on every
 * Node the app could plausibly run on, and it keeps the table in the typed file the app itself
 * imports rather than splitting it into a second source of truth to satisfy a build script.
 */
async function loadKinds() {
  const source = path.join(WEB, "lib", "notification-kinds.ts");
  const js = ts.transpileModule(fs.readFileSync(source, "utf8"), {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
    fileName: source,
  }).outputText;
  // Via a real file rather than a `data:` URL: a data URL cannot resolve relative imports, and a
  // future edit adding one to this module would fail in a way that points nowhere near the cause.
  const tmp = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "ih-swdata-")), "kinds.mjs");
  try {
    fs.writeFileSync(tmp, js, "utf8");
    return await import(pathToFileURL(tmp).href);
  } finally {
    fs.rmSync(path.dirname(tmp), { recursive: true, force: true });
  }
}

const { NOTIFICATION_KINDS, GENERIC_KIND } = await loadKinds();
const LANGS = ["en", "es", "fr", "de", "pt"];
const PREFIX = "notifications.";
const OUT = path.join(WEB, "public", "sw-data.js");

const messages = {};
for (const lang of LANGS) {
  const catalog = JSON.parse(fs.readFileSync(path.join(WEB, "messages", `${lang}.json`), "utf8"));
  messages[lang] = Object.fromEntries(
    Object.entries(catalog).filter(([key]) => key.startsWith(PREFIX)),
  );
}

// Every key the table references must exist in every language, or the worker would render a raw key
// on some device and not others. `check:i18n` guarantees parity across catalogs; this guarantees the
// table and the catalogs agree, which is a different claim.
const referenced = new Set();
for (const meta of [...Object.values(NOTIFICATION_KINDS), GENERIC_KIND]) {
  referenced.add(meta.titleKey);
  if (meta.bodyKey) referenced.add(meta.bodyKey);
}
const missing = [];
for (const key of referenced) {
  for (const lang of LANGS) if (!(key in messages[lang])) missing.push(`${lang}:${key}`);
}
if (missing.length) {
  console.error(`✗ build-sw-data FAILED — metadata references ${missing.length} missing key(s):`);
  for (const m of missing.slice(0, 10)) console.error("  - " + m);
  process.exit(1);
}

const banner = `/* GENERATED by scripts/build-sw-data.mjs — do not edit.
 * Sources: lib/notification-kinds.ts + messages/{${LANGS.join(",")}}.json
 * Consumed by public/sw.js via importScripts, which has no bundler and therefore no imports. */`;

const body = [
  banner,
  `self.IH_LANGS = ${JSON.stringify(LANGS)};`,
  `self.IH_DEFAULT_LANG = "en";`,
  `self.IH_KINDS = ${JSON.stringify(NOTIFICATION_KINDS)};`,
  `self.IH_GENERIC_KIND = ${JSON.stringify(GENERIC_KIND)};`,
  `self.IH_MESSAGES = ${JSON.stringify(messages)};`,
  "",
].join("\n");

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body, "utf8");

const kb = (Buffer.byteLength(body, "utf8") / 1024).toFixed(1);
console.log(
  `✓ build-sw-data — ${Object.keys(NOTIFICATION_KINDS).length} kinds × ` +
    `${referenced.size} keys × ${LANGS.length} languages → public/sw-data.js (${kb} KB)`,
);
